### ISSUE TITLE
ruby and gems for msf issues

### ISSUE THREAD

**Issue by uranium-waffles** [cSploit/android#156]
I know this issue has been brought up before but I feel the need to bring it up again. When I try to install the update for ruby it finishes and says cannot start process. I don't think much of this but it might mean something to someone. when I try to install the Metasploit framework update it finishes the download and says "an error occurred while installing the update." and without either the ruby update or the Metasploit framework update I cannot start metasploit rpcd and hence cannot use the sessions option and I also can't launch any exploits I Do not have a log cat right now but would be happy to supply one if needed.

**Comment by uranium-waffles** [comment]
Also i have a Samsung galaxy s5 rooted on android 4.4.2 kit kat.

**Comment by Azihak** [comment]
Same here!!!

I have logs from everything since the install. Because my connection is slow i stopped logcat while downloading MSF and start recording again at 96%. The steps were install, open, accept update core, accept update ruby, accept update metasploit, "error during download"

Install log:
http://pastebin.com/0BF3HVzA

First time open log 1 (installing core and ruby):
http://pastebin.com/BXaHtqya

First time open log 2 (failed installing MSF):
https://gist.github.com/Azihak/04065880afe3185c4340#file-gistfile1-txt
