### ISSUE TITLE
We need you with the best kit we can get you

### ISSUE THREAD

**Issue by flatpacked** [cSploit/android#177]
You're doing an amazing job, would you mind if I started a crowd-funded campaign to get you some decent laptops/servers/software ?
I know you're ato school but you sir, are a genius,  I am a hacker and pen tester but you have remarkable talent so if I can help contribute by doing a bit of crowd funding then I'm only too happy to help

**Comment by Qu1cksnap** [comment]
I wanna help too!!

**Comment by UrbanChrisy** [comment]
Sure do what you want.
Urb

Date: Thu, 28 May 2015 07:46:08 -0700

**Comment by Qu1cksnap** [comment]
You need to add a donation button somewhere so that i can atleast buy you a coffee!!

**Comment by Systemad** [comment]
http://www.csploit.org/donate.html

**Comment by tux-mind** [comment]
thanks for all you compliments guys, I'm not such special btw.

as @Systemad spot there is already a donate button.
last purchase were the `csploit.org` domain for 3 years ( about 50 $, all from donations ).

personally I'd like to purchase a pair of wifi adapters to play with cSploit and wifi cracking.

currently I'm using a notebook that a kindness guy purchased me for working on cSploit.
it's a T60. I love it because thinkpads are the best for writing code when you're around.

btw when working on cSploit I usually require more than 3GB of RAM and usually the boat slow down because it start using the swap. also android studio does not work very well on 1024x768 screens. at least 1hr of battery lifetime usually forces me to stop working.
but i love the keyboard and the trackpoint, simply awesome!
