### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by uranium-waffles** [cSploit/android#185]
On session stealing as soon as you fix the msf issue sometime soon I tried the stealer on my own amazon but it still asked for my password you should add the user name and password right next to the session kind of like zanti

**Comment by sorano** [comment]
Moved to #229

**Comment by gainan** [comment]
@uranium-waffles , the thing is if csploit captured an authentication cookie, which likely it wasn't. Could you assure that it was a valid authentication cookie? I say this because any site with cookies is added to the list.

In any case, when csploit captures a valid user session, usually the user's password has already been sent , thus we won't be able to display it to the user. And that would be in the case that we would be able to intercept users/passwords (from the session hijacker module), which for now we don't :)
