### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by DeveloppSoft** [cSploit/android#229]
Hello guys, I opened that issue so you will be able to share some ideas concerning cSploit.
Here is mine (working on it if @tux-mind thinks it clan be good):
- bluetooth hacking
- geo traceroute
- social engineering menu
  ... And a lot more

**Comment by Tajnymag** [comment]
- wifi cracking using USB card (workaround for any driver issue)
- on-device compiling of the newest cSploit code
- Router Keygen integration (the same range of supported routers)
- quick test for default credentials used in selected router's administration page
- automatic reporting of crashes and errors (combined with some simple on-server averiging)

**Comment by DeveloppSoft** [comment]
I can enable wifi cracking but it will need a patched android kernel..
To compile you can use the AIDE app.
I do not know what dayum is

**Comment by DomenlDruga** [comment]
By patching the android kernel you mean the mac80211 injection patch? Because Kali NetHunter has a [guide](https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel) on doing just that, so that everyone can patch and configure their own kernels.
Integration wit Router Keygen seems kind of pointless, as modern devices have enough resources to switch between two apps. Some automation could be implemented, but will only cause issues in the long run. 
The default credentials and tabbed interface would be very usefull.
"Dayum" is the over-pronounciation of "Damn".

**Comment by DeveloppSoft** [comment]
@DomenlDruga, yeah, I was speaking about that patch, then thanks for the
translation :smile:

**Comment by MuradTroll** [comment]
Metasploit Extra Console for Testing MSF Features, that arent currently included in the app. This could help to use exploits before they are even implented, and would help in research to make csploit features bigger.

But this is just optional. The main thing I want to get with this is: More features

Of course.

**Comment by gainan** [comment]
Hi,

- I´d like to have a complete suite for domain/subdomain analysis/discovery. Using dnsmap, dnsenum, fierce, whois, google (well, search.disconnect.me), etc... I think it would be easy to implement.
- dns spoofing using ettercap: I have it already implemented and working.

Anyway, I´m not sure if it happens only on my mobile (htc bravo 4.4.4), but there are a lot of problems with the latest apk/sources. 

For name a few: 
- login cracker not working (hydra segfault). This binary works fine: http://forum.xda-developers.com/showthread.php?t=2064605 but someone should compile the binary from the sources.
- passwordSniffer not intercepting SSL traffic (disabled by code: I´ve enabled it but the HTTPSredirector throws several SSLException when intercepting connections). Does anyone know why is it disabled? We could just use the ettercap plugin sslstrip, but it throws and error complaining about a cookie regex.
- network subnet does not always appear on the network list
- if when stopping the sniffer it exits with signal 11, cSploit displays an error and exits. I think it should not exit from cSploit, since the sniffer has already died and you can launch it again.

Has anyone seen these problems? I think I could fix some of them.

**Comment by DeveloppSoft** [comment]
@ga, I think we could try something like an OSINT tool.
Now some news: I found android pcap, an app which allow you to have a
kismet like tool with an external wifi card (without root), I will try to
use the sources for wifi cracking functionnality

**Comment by fat-tire** [comment]
Funny you should mention [android-pcap](https://kismetwireless.net/gitweb/?p=android-pcap.git;a=summary).  I was just playing with it yesterday, got it building w/gradle + the new tools in Android Studio.  FWIW, the [play store listing](https://play.google.com/store/apps/details?id=net.kismetwireless.android.pcapcapture) says that it's GPL, but I didn't see a notice about what version in the actual source code.

Anyway, right now it only supports a few [usb network adapters](https://kismetwireless.net/gitweb/?p=android-pcap.git;a=blob;f=src/net/kismetwireless/android/pcapcapture/Rtl8187Card.java;h=b8e1a44bb3a32376876ae1ff169634d1355ad568;hb=HEAD) specifically the rtl8187 card.  More specifically:

* Alfa AWUS036H, LevelOne WNC-0301USB v5, LevelOne WNC-0305USB (0x0bda:0x8187)
* AirLive WL-1600USB (0x1b75:0x8187)
* NETGEAR WG111v2 (0x0846:0x6a00)
* NETGEAR WG111v3 (0x0846:0x4260)

Unfortunately I don't have one of these :/  But anyway, to build with android studio and the newest SDK, you just need to change a few things:

1.  in [src/net/kismetwireless/android/pcapcapture/PcapService.java](https://kismetwireless.net/gitweb/?p=android-pcap.git;a=blob;f=src/net/kismetwireless/android/pcapcapture/PcapService.java;h=9416200b7a087c4422587e1e21489152ca8a6ce8;hb=HEAD) use a NotificationCompat.Builder instead of the deprecated notification.setLatestEventInfo().

2.  use this [build.gradle](https://gist.github.com/fat-tire/8f2546e623e019c7513d).  I cleaned it up (took out signingConfigs section just because I didn't have a key to point to) slightly from what I was using to build, but it should work w/o much effort.

3.  remove libs/android-support-v4.jar

4.  remove the versionCode/versionName and uses-sdk lines in AndroidManifest.xml

It would be nice to see support for other chipsets in there, but would have to create more UsbSource.java-type classes for each one, and they're not small.  But I haven't looked into it or more than 3 minutes.

If anyone can get Kismet Wireless to post which version of the GPL this uses, that would be great.  Their other [tools](https://play.google.com/store/apps/developer?id=Kismet+Wireless), particularly the cloudshark uploader, look interesting too.

ft

**Comment by DeveloppSoft** [comment]
@Fattire thanks, will have a look.
@tux-mind I will start working on all of that if you agree.

**Comment by sorano** [comment]
My idea is to have cSploit able to run also on a LAN interface.
For example on my nethunter pad I have USB OTG cable connected to an USB LAN interface. Currently I can only use csploit with WLAN.

**Comment by NoBody112** [comment]
Is it possible to implement a WPA2-PSK hash sniffer? 
The script would forcefully disconnect clients and then monitor the traffic for the handshake (which can later be cracked using PC). Thoughts ?

**Comment by DeveloppSoft** [comment]
I might try...
For the moment, I am trying to add wifi external cards functionnality, and
optimize the app.

**Comment by gainan** [comment]
@sorano, would you mind to add a new issue with your suggestion? I've got a patch which allows you to select a configured network interface, in case of no wireless interface available. I've tested it with just the mobile gms interface, and works fine.

Right now cSploit relies a lot on the wireless dhcp information to work properly, so for example, if you configure the mobile to work as hostspot, the dhcp information is not available and we can not use cSploit. From the command line ettercap works perfectly on this case.

**Comment by sorano** [comment]
@gainan Done. https://github.com/cSploit/android/issues/240

I love the idea of running cSploit on the GSM interface.

**Comment by DeveloppSoft** [comment]
@gainan, good, maybe you can do a pull request....

**Comment by Duartebm** [comment]
There should really be a HID (human interface device) attack so you could connect your cellphone on a pc and it would be detected as a keyboard and start typing programmed commands, just like Net Hunter (kali linux for android) and USB Rubber Ducky from Hak5. 
But I guess it would need to be able to do kernel changes for that... but anyways I think it would be possible to make some kind of automatic hack for when the cellphone is connected to a computer via USB (I remember there was an app that if I'm not wrong would automatically extract all saved passwords in a computer). 
Anyways, you understand my point, something that would work on USB :D .

**Comment by Tajnymag** [comment]
How about quicker merging of pull requests? There are even some from February :D

**Comment by DeveloppSoft** [comment]
Just to say that I am working on:
- a modern ui
- a lighter app (less lib), so it will be easier to compile
- adding RouterKeygen because it really impressed me
Will pull something as soon as possible.

**Comment by Tajnymag** [comment]
Thanks @DeveloppSoft. Really looking forward to it :-)

**Comment by gainan** [comment]
Another idea:
- MAC randomization when the app starts and prior to scan wireless networks.

**Comment by Tajnymag** [comment]
OK, I understand, it's a very low priority, but wouldn't it be cool to have a wearable support?

**Comment by DeveloppSoft** [comment]
Yeah, maybe.

**Comment by gainan** [comment]
I've added a new wiki page with all the ideas we have contributed:
https://github.com/cSploit/android/wiki/Ideas

If someone is working on any of these ideas, update the wiki with something like: <idea> <nick> WIP/<PR number>, or something alike.

**Comment by fat-tire** [comment]
I'm not quite sure what "on-device compiling of the newest cSploit code"  -- that sounds like the app compiles itself (?)

@Tajnymag what would wearable support look-like exactly?
@DeveloppSoft I saw you stopped by IRC...  come back!  Wondering what you mean by 'changing the cSploit architecture"

**Comment by Tajnymag** [comment]
@fat-tire I thought something like that. cSPloit would download latest code, compile a new apk, than prompt to install it. Tadaa, problem with nightly server is solved :smile: 

On a wearable could be displayed a list of on LAN devices or available exploits. With RouterKeygen added, wearable could inform you about "crackable" network. As I said, it's a very low priority :-)

**Comment by Systemad** [comment]
Isn't that basically the same as downloading newest version from github directly straight from the app and then install (which is what it already does). 
Nightly releases are not the same as stable releases.

**Comment by gainan** [comment]
new idea:
extend the session hijacker module functionality for:
- allow to detect users/pass fields on the URL.
- save not only the root domain of a cookie, but also all the pages the user is visiting within a URL.
- intercept not only web sites with cookies, but also without them
- allow to select which SSL cert to use.

**Comment by DeveloppSoft** [comment]
@Fattire, I leave IRC because I was using my Wiko OZZY which was closing
the page each time I was opening a new one.
By "changing the code architecture" I mean:
Have a cSploit android lib so the app is just the ui, it could be easier to
use (one repo for the lib, an other for the app).
Finally, I think time have come to launch cSploit 2.0 with a new ui and all
the new functionnalities, but maybe I am wrong.
Will come soon in IRC.

**Comment by gainan** [comment]
new idea:
- allow to use the port scanner and service inspector modules when selecting the whole network as target.

**Comment by sorano** [comment]
Suggestion from @Avamander #69

**Comment by sorano** [comment]
Suggestion from @cycroja #212 

Please let the app work without Wlan (This will be possible when #245 gets merged)

And maybe the MITM hitspot tethering option without internet.

**Comment by sorano** [comment]
Suggestion from @doringr #207 

will csploit have the new sslstrip+ or sslstrip2 in a near future?

**Comment by sorano** [comment]
Suggestion from @uranium-waffles #185 

On session stealing as soon as you fix the msf issue sometime soon I tried the stealer on my own amazon but it still asked for my password you should add the user name and password right next to the session kind of like zanti

**Comment by sorano** [comment]
I'll drop this in here even if it not high prio.

Suggestion from @BoBeR182 #112 
Will this project be looking to be distributed by f-droid?

**Comment by sorano** [comment]
Suggestion from @Avamander
#67 
Inform that host is disconnected when launching modules. (e.g. on "gray" hosts) or when running a module and the host disconnects mid-run.

#68 
Could you please improve the error messages? Just saying "An error occured does not help" also, it should auto report the error and known error should be numbered.

**Comment by tux-mind** [comment]
ok, let me answer to some of your great suggestions guys.

### RouterKeygen

personally I love unix philosophy: one program does one thing, and, hopefully, it do it good.
so my first thought about RouterKeygen was to give a link to the store to download and use it.

BTW, i gave a look at the [algorithms](https://github.com/cSploit/android/tree/v1.5.4/cSploit/src/org/csploit/android/wifi/algorithms) folder and I'm quite impressed of the number of WiFi AP that cSploit can reverse.
that code has been written by evilsocket for dSploit.

what are your suggestions ? integrate missing algorithms that [RouterKeygen support](https://github.com/routerkeygen/routerkeygenAndroid/blob/master/README.md) ?

as cSploit want to be a multi-platform pentesting suite I will have to port all these stuff into the core.  I'll have to write a C program that do it.

### geo traceroute

it would be useful only when tracing public IPs, and cSploit mainly work on internal networks.
so i think that this feature is quite useless.

btw a possible implementation is to:

  - [get all hop locations](http://www.telize.com/)
  - [get a visual path](https://developers.google.com/maps/documentation/javascript/examples/polyline-simple)

### router default password

there are 2 main problems for make it works:

  - we cannot detect the model of the router
  - there is no public API to get default password

I suggest to open the router webpage asking the user to find the model if not yet known.
than we will open [routerpassword](www.routerpasswords.com) and/or [portforward](portforward.com/default_username_password/) to let the user find it.

### crash reporting

crash reports are already working.

### UI improvements

up to you.

### Metasploit Extra Console for Testing MSF Features

absolutely!
sadly a ConsoleView is not so quick to make, just give a look at [TerminalEmulator](https://github.com/jackpal/Android-Terminal-Emulator) project.
we may expose a telnet bridge and use ConnectBot on local host.

### complete suite for domain/subdomain analysis/discovery

yep, once we switch to botbrew will be quite easy to build these tools.
search.disconnect.me sounds like a simple browser page to open :stuck_out_tongue_winking_eye:

> requires botbrew 

### Allow to select any network interface available on the system.

WiP.

> solves #212 

### MAC randomization when the app starts and prior to scan wireless networks.

workflow:

  - test if we can change the MAC to 11:22:33:44:55:66
  - reset back to original if succeeded
  - ask user if want to randomize MAC if it's interface driver supports it.

> requires botbrew to compile macchanger or ip2route

### cSploit compile itself

no sense.

I was joking, let me explain you @Tajnymag .
on your phone there isn't the tools required to compile an apk, thus the nightly must be compiled somewhere else.

### wearable gadget

we can develop a remote control app for cSploit ( thus to let you walk around while looking your watch for routers with known key algorithms ).
I think that the notification is too boring. I find the default "notify when an open wifi is found" settings is very boring, don't you agree ?

### session hijacker module

Many functions of the MitM module must be moved into the core.
a draft of the new proxy has been written [here](https://github.com/cSploit/evilproxy).

the most important feature IMHO is to use SSL Split instead of SSL Strip, it can bypass HSTS and the end user will se a waning, not an SSL error.

> solves #207 

### changing the code architecture

this is what I'm trying to do by moving all the big functions into the core.

but we cannot move everything into the core.
please suggest some concrete example so we can discuss it.

### port scanner/inspector on whole net

do you mean running those tools agains all knows targets, right ?

### ping tool

will be merged into `complete suite for domain/subdomain analysis/discovery`

### F-droid

yep.

> requires botbrew

### notify when host disconnect

ok, low prio.

### improve error messages

hem.. yes, someone will take care of this :smile: 

### not understood stuff

  - bluetooth hacking
  - social engineering menu
  - tabbed interface -> multiple attacks/scans at once
  - add the user name and password right next to the session

**Comment by gainan** [comment]
**port scanner/inspector on whole net**
yes, select the subnet and allow to scan it, like nmap -sS -P0 192.168.1.0/24

**complete suite for domain/subdomain analysis/discovery**
I mean to use some webs to extract more info, aka google dorks (site:xx inurl:xx ...) :)

**Allow to select any network interface available on the system.**
Will you do it? Up to you, if you want I can adapt it to the latest changes, or feel free to start it from scratch ^^

**Comment by gainan** [comment]
new idea:

since the service inspector and login cracker depends on a previous port scan, when finish the port scan display 2 buttons: [service inspector] [login cracker]

**Comment by DeveloppSoft** [comment]
Bluetooth hacking:
- devices spoofing
- bluesnarfer attacks
Social engineering:
- backdoor files (msfvenom)
- spoofed SMS
Etc...
Working on botbrew.

**Comment by Megaeloelo** [comment]
Is it possible to run msfconsole in Csploit to create exploits? Sorry for bad english .

**Comment by Megaeloelo** [comment]
Something like port of Metasploit . Sorry for spam .

**Comment by tux-mind** [comment]
@gainan google dorks sounds fine, but they are useful to find hidden resources on some webserver... I cannot understand how these stuff can be useful in an internal network. it's more related to a OSINT app then a penstesting one IMHO. nut maybe I'm wrong, pleasze show me how you suggest to use it :wink: 

I'll test your pull request when I get home, there I have a TF201 with an USB port.
as I said, that pull request must be merged :wink:

@DeveloppSoft I'm new to bluetooth hacking, however it sounds interesting. the social engineering feature it's cool, especially combined with the bluetooth hack. I can imagine that you can record a conversation that you triggered with a fake SMS.

also the ability ti infect any file with any payload it's simply awesome.

**Comment by tux-mind** [comment]
@DeveloppSoft about notbrew, how does it launch dynamically linked executables on android ?
does it play with the `LD_LIBRARY_PATH` environment variable ?

thanks for your time :blush:

**Comment by Megaeloelo** [comment]
Idea :
Csploit working in hotspot .

**Comment by DeveloppSoft** [comment]
@tux-mind, here is the  [manual] (http://botbrew.com/manual.htm)

**Comment by gainan** [comment]
guys, we've started converting all these suggestions into new issues, in order to let @tux-mind categorize and prioritize them. So if you have any new suggestion, check first the already opened issues and comment/contribute to that ones, and if it's not created add a new issue.

**Comment by tux-mind** [comment]
@gainan please lock this issue once all those great ideas has been converted to issues.

thanks to all for your interest and help :blush:

**Comment by gainan** [comment]
@DeveloppSoft, would you mind to add your suggestions in several issues? I think you can explain them better than me :)

@Megaeloelo, that feature will be possible when this pull request will be implemented: #245. However it'll need additional work, because AFAIK the tethering option inserts

**Comment by DeveloppSoft** [comment]
Hey guys,
@ga, of course, just give me some time.
@tux-mind, I hope my link was useful, if you want, you can contact me on my
personnal email address (I think you can find it :smile:)

**Comment by pgolecha** [comment]
An option to stop all running process and exit because currently I cannot find a way to stop metasploit rpcd ,closing the app does not seem to work

**Comment by evertking** [comment]
Any chance that P2P-ADB might be an option? Love the app!! Its came so far in the past few weeks! Tux YOU ARE the man!!!!

**Comment by mcilya** [comment]
Add Estimated time for inspector module

**Comment by tux-mind** [comment]
@evertking thanks for the compliments, but we get so far only thanks to all other great contributors :wink:

anyway please open an issue for the awesome [P2P-ADB](https://github.com/kosborn/p2p-adb/) idea if you didn't yet.

@mcilya I think that someone was already working on it :wink:
we talked about it on freenode.

**Comment by evertking** [comment]
Would it be possible to have an option to create a     apk and send to a target to exploit an android phone?

**Comment by Tajnymag** [comment]
Or an Stagefright aware media?

**Comment by evertking** [comment]
@tux-mind I know this is a bit off topic ;) but where would you suggest as a starting point for a noob to start learning so one could jump in here and contribute? All I have is a laptop.

**Comment by evertking** [comment]
Just one more noob request ;) maybe a cSploit scripts add on like dsploit but more geared toward pentesting? Can that even be used for testing or is that more like pranks? Where can I donate at to help ya out in anyway.
Again thanks for all your hard work, everyone. This app has peaked my interest and find my self spending a lot of time checking for updates and trying to learn. Its shocking how easy it is to take data and to spy and this app opened my eyes to that. And with mobiles being such a large part of everyday life its a must, I think. Test and secure it or risk it. I'm very thankful to you and to have found this! 
OK I with end my rant and get busy taking windows off my laptop and throwing on linux

**Comment by tux-mind** [comment]
@evertking first step to become an adavanced user ( aka uber ) it's to install Linux :wink: 

probably learning a new sexy OS will require some weeks or more.
as start point I suggest you to use Ubuntu, an easy to use linux distibution.
once you learned quite well how to play with a terminal you can more forward to ArchLinux, one of the most used distro by advanced users.
if you get crazy and want to really understand how every part of your pc works give a try to Gentoo linux.

btw those are my suggestions for became a linux expert, not a contributor.

for contribute to cSploit you can also use a windows PC, installing android studio on it.
you need to learn Java and some basic of the Android SDK.
anyway contributions can be made in many forms.

once you installed AndroidStudio you can also open the translation editor to help us translate the application into your language.

For donations give a look to the [donate page](http://www.csploit.org/donate.html).
I have to switch to another donation system thus to give you a way to see how much we raised.

about your idea of "sending" an apk to other phones: using the MSF we **will** be able to infect downloaded objects.

a cool feature that require some cool work :wink:

and thanks for your impressions, will post them on the official website if yo agree :blush:

**Comment by uranium-waffles** [comment]
I like how in the latest nightly it added port scan at startup like zanti and I think we should add to that by automatically doing service inspector and exploit finder at startup and putting the exploits found next to the ports found open. I would do this myself but I'm just now learning java in order to use android studio so I can help.

**Comment by tux-mind** [comment]
@uranium-waffles service inspection is too deep and heavy IMHO.

we already encountered some performance issues with the stealth syn scan ( aka fast scan ).
furthermore using the Inspector will make any IDS detect you.

I think that it can be a bad idea.
you can scan all the hosts using the multiple selection from the main screen.

it can be acceptable if we can scan networks with the service inspector, this will use a single process but will not solve the IDS problem.

however if you are using cSploit you really don't care about IDS...

so maybe will do, unsure right now

**Comment by uranium-waffles** [comment]
@tux-mind how about an intrusive scan option? In zanti2 if you press the refresh button for a rescan a drop down menu appears and allows for selection of an intrusive scan that scans for vulns. That way we could switch between the two. (Non intrusive and intrusive)

**Comment by fat-tire** [comment]
I think this could be done, but it's my understanding that the longer, slower scan takes a ton of resources, both generating a lot of network activity and taking up cpu/battery/memory.  I was reminded today that thre are local networks with thousands of hosts...

That said, I don't see any obvious reason not to make it an option-- either from a drop down menu or a toggle in the settings to use regular vs. extra-crispy port scanning by default.  The latter would give you the vuln count...

If there is a lot of enthusiasm for this, it could be an option.  @tux-mind I imagine this isn't something like the nmap network portscan that could be done "in bulk"... you'd have to inspect each host independently...  wonder how many hosts a typical device could do simultaneously before choking....

**Comment by gainan** [comment]
In my (*personal*) opinion, I think that these options belong to the subnet card/window, and adding them to the app start up is redundant. On the other hand it has no many sense to have these options on the main window, and not on the subnet card/window.

I guess this is about how each of us understand how cSploit should work :) The initial arp scan is just fine for me, to give you an overview of the subnet you are on, and for select targets. Successive actions should be perform on demand.
It's also true that the initial port scan allows you to select targets, and having an option to allow it on the app start up is ok for me (default to on would be a bit annoying).

**Comment by uranium-waffles** [comment]
3 suggestions I found very interestong that are not on the todo list are Stagefright Aware Media, Geo-Traceroute, and HID attacks where you plug into a computer and you can execute commands.

**Comment by uranium-waffles** [comment]
Also how about bettercap integration? http://www.bettercap.org/ made by evilsocket It is like ettercap but better hence the name bettercap.

**Comment by tux-mind** [comment]
@uranium-waffles I think that bettercap is a great project, but is in it's early days let check up together why is not a good choice right now:

  - ruby is slower then C
  - ettercap has more dissectors ATM
  - both [bettercap](https://github.com/evilsocket/bettercap/blob/master/lib/bettercap/sniffer/parsers/httpauth.rb#L35) and [etttercap](https://github.com/Ettercap/ettercap/blob/master/src/dissectors/ec_http.c#L788) does not have a callback
  - ettercap [stores credentials](https://github.com/Ettercap/ettercap/blob/master/src/dissectors/ec_http.c#L782) in a shared point, where we can found them

I'm not talking about parsing their output, we've scheduled ( from a lot of time ) to move all the MITM stuff into the core, it will be stupid to rewrite all protocol dissectors, just reuse what has been already wrote and tested from years, use libettercap. actually bettercap does not provide any library.

sorry for the short answer but I've to go right now :grin:

**Comment by Pr0xy671** [comment]
Advertisement Button
===============================================================================
An idea I have was a button in the cSploit settings where you can turn it on and off. 

If you turn it on, you enable ads in cSploit and the ads will support the devs. 

If you turn it off, you remove the ads and cSploit is like back to normal. IMO this will help out the devs a lot.

**Comment by Megaeloelo** [comment]
@Up This is a nice idea .

**Comment by fat-tire** [comment]
I kinda like the idea, except speaking only for myself-- i don't want any money.

I think @tux-mind could use some revenue to offset his expenses (domain name registration, web site + bandwidth, beer?).  So if he wants to set up an Admob account or something, it would be very simple to incorporate ads.

A license concern though-- Admob in particular would involve a dependency on a Google library (play-services-ads), which is closed source.  Not sure how that would be compatible, [license-wise](https://www.gnu.org/philosophy/android-and-users-freedom.en.html), with the GPLv3, cSploit's license.

Distributing the cSploit code itself on github may fall under the [Linking exception](https://www.gnu.org/licenses/gpl-faq.html#FSWithNFLibs) -- the source code only refers to the closed library.  But the app binary itself?  Not sure.  But the FAQ seems to suggest you could distribute the app only without the library, which would be pointless for an .apk...

**Comment by Rubenoo** [comment]
Why can't you just make a standalone simple app with like a calculator or something and then advertising's everywhere to support csploit?

**Comment by BoBeR182** [comment]
-1 for adds all you need is a bitcoin address in the about page or paypal set up. If you really wanna make more money set up a script that replaces adsense ads with your own ads for MiTM networks.

**Comment by Pr0xy671** [comment]
MitM script that replaces their regular ads with your ads...dirty, but awesome. 

*high fives*

**Comment by tux-mind** [comment]
thanks for the suggestions guys.

@fat-tire thank you for pointing out the license problem.
I'm quite away of all that law stuff, I just want to worry about writing code :grin:

lemme known what is the best way to raise some money and I'll start working on it ASAP.
I recently started a campaign on pledgie to buy a new notebook.
 
I'll try to make every incoming donation and outcoming purchase public, thus to allow you to see where your moneys goes.

yours, tux_mind.

**Comment by Vinesh123** [comment]
user new tool in csploit
DOS attack

**Comment by BoBeR182** [comment]
@tux-mind maybe start something on BountySource and see if anyone wants to fund bugfixes and thus pays for your time.

**Comment by Somebodyhura** [comment]
Hi
I saw one of your goals is to crack wifi passwords.
There are many ways as you know and wps is the fastest.
I suggest wps connect:

http://www.pfrox.site40.net/

As it's a free app I think the dev will agree for its source code to be added to csploit by mentioning the credits of that section is for them OR the androdumpper:

https://www.linkedin.com/profile/view?id=AAMAAAVKhNMBg5PU0s4M01AIF3H_5uFfn7lLrHg

Just like wps connect but can brute force wps too.

You may ask why implement such a thing when there it is available...but I say all-in-one is always different.

And there is something else called WIBR+ that does brute force on the router(not wps...the real password)
It's like hydra... Or dictionary attack and it supports masks too...like sometimes I hear they say 110043XX so I go WIBR and as the other 2 digits are numbers so it tries and bingo it finds it...

http://forum.xda-developers.com/showthread.php?t=2398114

**Comment by DeveloppSoft** [comment]
Hey @Somebodyhura, I am taking a lok, thanks !

**Comment by pahapoika** [comment]
Maybe something like https://github.com/jackgu1988/dSploit-scripts

Maybe graphical gui where you can add those scripts to script injection. No need for writing those could be good for noobs. :)

**Comment by pahapoika** [comment]
And https://github.com/n1nj4sec/pupy could be very useful too. It would be added to exploiting module. 

Also i think automated msf payload generator would be cool. (See https://github.com/cSploit/android/issues/579 )

**Comment by Somebodyhura** [comment]
And for the other goal ( install backdoor for later access)...

How about androrat? 
Well I just heard of it...I haven't tested it but as its a rat...it should do remote administration and can make installing a backdoor possible

( somehow using the packet editor and replace the apk with Androrat so the victim will install it and its done but mostly as I see users check the apk icon...and see its not matching to what they want...somehow not going to work)

( and I think of an very difficult way to bind apk editor to csploit so apk will be downloaded to attackers phone, extract icon, replace with androrat icon, and maybe add useless bites to make same size...this should better work...permission are never problem cuz...even me don't check them :D)

**Comment by Xmashine** [comment]
New easy-to-add but powerfuel idea to add at the main menu attack. This is a special type of DOS attack directed on a special LAN node. It can be used to exec massive attacks on a single device, and to crash it.

The way to implement this feauture is follow these steps:

1. Add a new contestual-menu card named DOS attack in the main menu
2. Create an activity to SetUp the attack details, such as victim IPv4 and IPv6 address, MAC adddress, OS type, and other tech data. At the end of page, a button who will start attack
3. Implement in daemon the basic DOS C++ files and headers
4. Create a function called first to launch the attack who change your NET configuration faking your spech and making your device unreachable by network inspections tools.
5. Try to send an abnormal quantity of ping data using thread's engine same as LOIC

**Comment by BoBeR182** [comment]
@Xmashine Mass amount of pings will not crash a machine these days, just slow down their internet connection. Your better bet to create a DOS would be to use the ARP injection attack and just drop all packets from the machine, this is already implemented.

**Comment by DeveloppSoft** [comment]
Outdated
