### ISSUE TITLE
Metasploit dont start

### ISSUE THREAD

**Issue by asbtlt** [cSploit/android#246]
Hi all, i have final version cSploit, bup metasploit dont wana update and start. What i do wrong?)

**Comment by Rubenoo** [comment]
Hey @asbtlt, The developers of Csploit are aware of this bug with metasploit. and there are currently working on a fix. until the fix is made we have to wait. but please before making a discussion please check is there are other people with the same problem. because this is the 1001 threads about this problem. #Close please.

PS your not doing anything wrong exept for not reading the other problems correctly :P

**Comment by asbtlt** [comment]
Thank u for answer! Sory for ir

**Comment by Rubenoo** [comment]
It's ok, and thanks for closing this thread
