### ISSUE TITLE
Launching exploits doesn't work 

### ISSUE THREAD

**Issue by Tajnymag** [cSploit/android#253]
OK, after the mighty update gems install correctly, but I found another problem. When I open the exploits section, find all available exploits, I am not able to launch any of them. Payloads don't seem to be chosable and after clicking "Launch all exploits" nothing visible happens. Is it just me or is it supposed to work like this? :smile: :smile:

**Comment by uranium-waffles** [comment]
No this is not just you and I highly doubt it is supposed to work like that. These exploits i find are metasploit exploits and should work, I thought this update was the one that fixed it. But it didnt work for me either.

**Comment by Systemad** [comment]
Once you open cSploit you'll have to wait up to 5 min until you see a toast message saying "connected to MSF RPC daemon". 
Then you will have to " Launch" option.

**Comment by Rubenoo** [comment]
When i launch its said: launch failed. and when i select another payload and then launch the apps crashes.

(samsung galaxy s5 android 5 rooted)

**Comment by Tajnymag** [comment]
I think cSploit can't connect to the daemon. I've been waiting for more than 9 minutes and nothing has happened

**Comment by Rubenoo** [comment]
It said to me: connected... and then daemon returned #1 is that good or not?

**Comment by swelit** [comment]
It doesn't work for me either

**Comment by sorano** [comment]
I know we are all eager to get csploit running but these "it doesnt work for me either" does not really help to move the project forward, as with any development logs or something that points towards the problem is needed to find the issue.

Like someone said, there should be a howto on filing bug report's.

At least start with installing catlog: https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=sv

Then read this:
http://forum.xda-developers.com/showthread.php?t=1726238

That should give a starting point in getting the logs, then upload them to pastebin and link them along with your comment in the issue.

Offtopic:
swelit, är du svensk? Kom in på irc så kan vi prata mer.

**Comment by Tajnymag** [comment]
OK, then [here](http://pastebin.com/dNzrS11t) is my log.

**Comment by tux-mind** [comment]
@sorano you're absolutely right.

@Tajnymag thanks for the log.

I suspect that you do not receive the notification about the msfrpcd started, in fact you received it just a moment before it has been shut down ( because you closed the app or start/stopping it from the menu )

have to investigate better...

thanks for the report.

**Comment by Tajnymag** [comment]
@tux-mind That's true. I don't get any notification about msfrpcd started. Also this is the reason, why I manually tried restarting Metasploit while recording the log. I tried running the app for some time without my interaction, but msfrpcd didn't start even after 10 minutes.

**Comment by MuradTroll** [comment]
I have a problem when trying to open the tab Exploit scan. I can open it and it shows me some of the exploits, but When I press "Options", I get a blank screen and nothing really happens. Also when I press "Payloads" I usually get nothing in the dropdown menu.

**Comment by tux-mind** [comment]
please wait, I've already found the problem and I'm fixing it.

**Comment by MuradTroll** [comment]
Ok :) @tux-mind I have a question. Since my insternal app memory is REALY low, I had to move the msf and ruby folder fron /data/data/csploit.blah.blah/ to my external sd card. Now, is he problem related to msf or ruby? Or is that an core or app problem. Do you know a way how I can extend the app memory? Like I have 4 Gb internal memory but only 700mb for Apps?!??!?!? and the holf of this takes google apps. 

Also is there a way that I can directly download all the stuff to my sdcard?

**Comment by tux-mind** [comment]
should be fixed, but I cannot test it. I have to wait that #244 get fixed.

**Comment by hipopcorn** [comment]
thaaanks @tux-mind i am just waiting for this fix to donate to you!!!

**Comment by tux-mind** [comment]
@MuradTroll i worked a lot to allow cSploit to work with an external
installation of the MSF and ruby. It should not be a problem.

For downloading stuff just give a look to the releases pages of the MSF and
ruby project, there you will find the stuff to put on your sdcard for local
update. After a manual installation cSploit will keep ask you about
upgrading MSF and ruby, because he do not known which version you manually
installed, you can disable update checks from settings.

MSF - github.com/cSploit/android.MSF/releases
Ruby - github.com/cSploit/android.native.ruby/releases

**Comment by tux-mind** [comment]
the problem was composed by 2 issues:

  1. `msfrpcd` uses a buffered output, which will leave us waiting forever for the "I'm ready" string.
  2. `msfrpcd` is ready about after 2,5 minutes after the "I'm ready" string...

the first problem has been fixed in cSploit/android.MSF@852f6a6fb0054e428ef02da503003383959c56f1

and I'm working on fixing the second.

**Comment by MuradTroll** [comment]
@tux-mind ok thx but do you think just downloading it and putting it on my sd will solve? Right now I have it on sd but I moved the content from data/data after the installation complete. 

I mean will this method (manually) install ruby msf gems too?

**Comment by madmarcs** [comment]
So, today nigthly build will work correct?

**Comment by uranium-waffles** [comment]
@madmarcs yeah the nightly build works but for me it crashes whenever i click sessions and exploits are found a lot slower than when msfrpc is not connected

**Comment by tux-mind** [comment]
@MuradTroll please read carefully before posting.

@uranium-waffles searches are always performed online, querying rapid7 and exploitdb, msf connection status should not change search duration.
please report if you see that I'm wrong, I'll make some test.

**Comment by tux-mind** [comment]
@Tajnymag no it is not working yet, we are still working on fixing bugs.

**Comment by tux-mind** [comment]
ok, fixed on the develop branch, try the nightly apk in the next hour and let me knwon :v:

**Comment by hipopcorn** [comment]
Tux, it stills the same, i cant see Any payload

**Comment by hipopcorn** [comment]
Sorry!! It was about 20 min!!! Okay i will teste and tell you

**Comment by hipopcorn** [comment]
@tux-mind it's crashing for me too!! My log file here http://pastebin.com/vX3Wsy64

**Comment by hipopcorn** [comment]
My device: moto maxx, cyanogemmod 12.1

**Comment by madmarcs** [comment]
09-25 12:11:26.398 E/CSPLOIT[services.MsfRpcdService.connect](27601): java.net.ConnectException: failed to connect to /127.0.0.1 (port 55553): connect failed: ECONNREFUSED (Connection refused)

On last build.

**Comment by tux-mind** [comment]
@madmarcs that's not a real error, I have to fix logging n that part.

@hipopcorn thanks for the logcat, I'll work on it ASAP.

**Comment by madmarcs** [comment]
Sorry I will send u the logcat ASAP.

**Comment by tux-mind** [comment]
@hipopcorn the log you posrted is of the daemon ( cSploitd.log )
for debugging crashes I need the logcat ( you can record one with the catlog app ).

thanks for your time :blush:

**Comment by hipopcorn** [comment]
@tux-mind  for me if i choose to search for exploit, i need to wait about 15 seconds to click on edit options, if i dont wait it crashes, but if i wait, i can do all the things, but i can`t just see any payloads, do you still need my logcat? cause i don't know how to save it, but i know this is the logcat error: 09-25 15:40:00.819 E/CSPLOIT[services.MsfRpcdService.connect](13323): java.lang.NumberFormatException: invalid IP address

**Comment by tux-mind** [comment]
@hipopcorn as you copy and pasted that line just copy and paste the whole logcat :wink: 

if you create a gists or use pastebin will keep this conversation clean and readable.

thanks for all your porecious time :blush:

**Comment by Rubenoo** [comment]
When i tried to launch a exploit on the latest develop branch it crashed
samsung galaxy s5 android 5
logcat : https://gist.github.com/Rubenoo/f0013f279f4eaaf01741

**Comment by tux-mind** [comment]
@Rubenoo should be fixed in 65d0478

**Comment by Rubenoo** [comment]
i was launching some exploits
it didnt crashed but nothing happend
it only said job started
and then i tried another exploit and tried to launch and it crashed
logcat : https://gist.github.com/Rubenoo/616371939c0f22b62557
samsung galaxy s5 android 5

**Comment by tux-mind** [comment]
fixed in cbb966c

**Comment by madmarcs** [comment]
@tux-mind  here is my catlog. 

https://gist.github.com/madmarcs/0be97d3cc993a4acaf88

**Comment by hipopcorn** [comment]
@tux-mind sorry but, now i can choose an exploit, but i can't launch it, when i launch, it crashes

**Comment by hipopcorn** [comment]
@tux-mind okay its all working fine, but when i Try to launch the exploit it crashes,
Log file: http://pastebin.com/K7pDakW3

**Comment by tux-mind** [comment]
@madmarcs no usefult info in your logcat, please capture it after the problem occurs, i suggest you to use catlog from play store.

@hipopcorn thanks for the logcat, that crash was fixed in 65d0478 , are you using the latest nightly ?

thanks in advance for your time guys :blush:

**Comment by madmarcs** [comment]
@tux-mind Sorry i take the logcat before the error, this is the correct one.
The app force close after launch a exploit.

https://gist.github.com/madmarcs/3ffd6ed1ddb9e98ecfaa

Other thing that I see, is the RPCD that take almost 5 min to connect.

**Comment by hipopcorn** [comment]
@tux-mind with nightly its worst, it crashes when i search exploits AMD Goes to start rpcd

**Comment by hipopcorn** [comment]
@tux-mind the same error happening no mattee what version i use, every time i launch it crashes

**Comment by hipopcorn** [comment]
@tux-mind my logcat:http://pastebin.com/sHz18MuU
Obs: my language is portuguese

**Comment by Settix** [comment]
Hi @tux-mind :)
Nmap doesn't recognise my target ip's os ( my mac is listed as a phone running ios on the inspector tab ) we could maybe tweak nmap's parameters to get a more precise os recognition and integrate the results of the port scanner in the  inspector tab ( in order not to do a port scan again ). Exploit finder lists a shellshock and a windows exploit. Tried both, no one worked.
I'm running the latest nightly on an xperia z3.
Here's my catlog : 
https://gist.github.com/Settix/38e96a52998d81955469
Thanks for your time tux ;)

**Comment by tux-mind** [comment]
@xaitax can you check nightly build status ?
logcats show a stacktrace incompatible with sources from the develop branch.

thanks in advance :blush:

**Comment by tux-mind** [comment]
@Settix ports found by the port scanner are used by the inspector if the "focused scan" menu option is selected.

I agree that advanced used should be able to tweak nmap parameters, but please make a new issue, thus to assign the right flags to it :wink:

**Comment by tux-mind** [comment]
seems fixed with last commits. closing.
