### ISSUE TITLE
Ruby dos't update

### ISSUE THREAD

**Issue by asbtlt** [cSploit/android#257]
Hi,
Ill reinstall new version cSploit 1.5.4. Core update Ok. Ruby dosn't update. This is only my problem?

**Comment by sorano** [comment]
@asbtlt 

Ruby updated fine on my pad, so I fear it's only your issue.

I would try to fully uninstall the old cSploit then reinstall the latest release.

**Comment by asbtlt** [comment]
So, ill make full uninstall old version and can't update ruby now

**Comment by sorano** [comment]
And you have supersu(along with granted permissions to cSploit?) and busybox installed? Have the older versions worked for you?

In that case logs are needed in order to troubleshoot the issue:

Dtart with installing catlog: https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=sv

Then read this:
http://forum.xda-developers.com/showthread.php?t=1726238

That should give a starting point in getting the logs, then upload them to pastebin and link them along with your comment in the issue.

**Comment by asbtlt** [comment]
Thank for you help! @sorano ii know that ill do wrong. My BustyBox was installedin /system/xbin i reinstall it to/system/bin and all was to work!
