### ISSUE TITLE
RPC MSF Not connected on Galaxy S4 i9505

### ISSUE THREAD

**Issue by akremche** [cSploit/android#268]
RPC MSF Not connected on Galaxy S4 i9505

**Comment by Rubenoo** [comment]
I know we are all eager to get csploit running but these "it doesnt work for me either" does not really help to move the project forward, as with any development, logs or something that points towards the problem is needed to find the issue.

Like someone said, there should be a howto on filing bug report's.

At least start with installing catlog: https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=sv

Then read this:
http://forum.xda-developers.com/showthread.php?t=1726238

That should give a starting point in getting the logs, then upload them to pastebin and link them along with your comment in the issue.

tnx to @serono
