### ISSUE TITLE
Dark Theme doesn't show

### ISSUE THREAD

**Issue by hipio** [cSploit/android#276]
I just downloaded and installed the latest Nightly build of cSploit and it doesn't matter what I do, the dark theme does not appear. Yes, I quit the app completely after changing the setting. Yes, I have switched the switch a few times to no avail.

**EDIT**: It seems that the text parts did change to reflect the #258 issue, but the main screen is as white as a snowflake.

**Comment by tux-mind** [comment]
@hipio try to terminate cSploit from `Settings > Applications > cSploit`.
thanks for the report :blush:

**Comment by hipio** [comment]
Like I said, I quit the app completely. Force quit, not in cache, gone.

2015-09-24 23:00 GMT+02:00 tux-mind <notifications@github.com>:

**Comment by tux-mind** [comment]
oooook... so you open the app and ? see only a white screen ?

I think that I've already found the problem but it require some work to fix it :stuck_out_tongue_closed_eyes:

**Comment by hipio** [comment]
@tux-mind Well, I find the standard white theme, yes. But when I press on an IP to do something, I see everything like  #258.

**Comment by tux-mind** [comment]
I do not understand, sorry.
can you post a screenshot of the first screen you see ?

thanks for you patience :blush:

**Comment by hipio** [comment]
Here you go. This should be dark, but it isn't.
![screenshot_2015-09-24-23-40-29](https://cloud.githubusercontent.com/assets/3717518/10087712/eed8cacc-6315-11e5-842b-8290c39fbb03.png)

**Comment by tux-mind** [comment]
woooop.... that's strange... @fat-tire any clue ?

I suggest to retry when #258 will be fixed, probably this is related.

**Comment by fat-tire** [comment]
@hipio what version of Android are you using?  I haven't seen that before, but again, the Dark theme is screwy simply because no one has messed with it.  Someone could fix it just by playing with the various defaults-- I'm not really a UI person, so if anyone wants to play with that `styles.xml` file, this could be fixed pretty quickly I think.  It's one of those things where aesthetic taste will really make a difference... what do you want a dark theme to look like?  [Make it so](https://github.com/cSploit/android/blob/develop/cSploit/res/values/style.xml)!

**Comment by tux-mind** [comment]
@hipio some recent changes has been made to fix #258 , please try out latest nightly and let us known if your problem has been fixed.

thanks in advance for your time :blush:

**Comment by hipio** [comment]
@tux-mind Sorry for responding so late. I have Android 5.0.2 and the recent changes to #258 seemed to have worked for me as well. Thank you!
