### ISSUE TITLE
Job started... , now what? 

### ISSUE THREAD

**Issue by Krossom** [cSploit/android#325]
I have already started an exploit and it's successfully launched. Well I suppose that cause it's say job started. But I don't know where  can I see it... Now what have to do?

**Comment by fat-tire** [comment]
@Krossom check out this [WIP](https://github.com/cSploit/android/wiki/Tutorial-%231----Use-cSploit-to-get-root-shell-on-Metasploitable2) for what to expect. (doing screenshots for it now).

**Comment by Krossom** [comment]
Thanks @fat-tire but I can't see the button shell and sessions don't work  (it say me no sessions are on)  :c

**Comment by fat-tire** [comment]
@Krossom It's possible that although it was launched successfully, the exploit itself failed.  There was a discussion this afternoon about how best to show that (since I guess metasploit doesn't have some kind of "didn't succeed" message, though I did think somehow other UIs are able to relay that info...)   Anyway, i added some screenshots for what it SHOULD look like if there is a success.

I don't know much about Metasploit honestly, but I think it's possible that payloads can return things besides root shells such as web servers and such--  wish I could be more help with this but maybe someone else will know.  You can always try metasploitable as in the tutorial though if you're just testing and want to see if it works for you.

cSploit is just getting a ton of fixes in the last few days, so things are moving fast... there might be a better way to report back if a "job' was created or not... watch this space :)

**Comment by Krossom** [comment]
Well thanks you very much  @fat-tire, I'm going to close this issue. 
Yeah, things go fast so I'm going  to wait the next update. 
Lucky you, great team ;3
