### ISSUE TITLE
Crash while searching for exploits

### ISSUE THREAD

**Issue by pgolecha** [cSploit/android#327]
Here is the log 
http://pastebin.com/rTJTqsdr
Csploit crashes while searching for exploit

**Comment by maddog9696** [comment]
Have same problem. When ran agianst a host with 2 open ports exploit finder runs and shows exploits, no problems! But when ran against a host with either 6 or 7 ports/services, exploit finder fails and Csploit crashes. Have tested this a few times, it works with some hosts (targets with few open ports/services), always crashes with other hosts (tragets with 5+ ports/services running).

Samasung galaxy tab pro 8.4
Cyanogenmod 12.1
Rooted and busybox installed
Latest pre release and nightly's
Will post logs when home on device

**Comment by gainan** [comment]
> org.csploit.android fatal error : unknown option type: addressrange
09-29 13:53:18.881 E/ACRA    (27571):   at org.csploit.android.net.metasploit.Option.<init>(Option.java:55)

The problem is that we fire a RuntimeException intentionally when we find an unknown option, so we force to close the app on Option.java:55. @fat-tire @tux-mind , you have a deeper knowledge of this area, is it mandatory to exit from the app at this point?

**Comment by rednas0812** [comment]
i have the same problem

**Comment by tux-mind** [comment]
@rednas0812 please provide a logcat, so I can spot the problem :wink:
