### ISSUE TITLE
Heartattack

### ISSUE THREAD

**Issue by Systemad** [cSploit/android#33]
I downloaded csploit nightly today, and every time I start the app . Screenshot http://imgur.com/uiaCrt8

**Comment by tux-mind** [comment]
@keaneokelley thanks for the report.
building it statically will fix the issue, but will increase binary size.

since the daemon it's a long-lived process i prefer to provide 2 different versions of the binaries.

please open a new issue so i can refer to that one.
this is related to an old mistake i made with a pull request.

**Comment by tux-mind** [comment]
@keaneokelley nevermind, it has already been reported in #18 .

will fix ASAP.
