### ISSUE TITLE
Sessions not avaliable

### ISSUE THREAD

**Issue by PTZema** [cSploit/android#341]
Hello
When I sucessfull launch a exploit and the "Job started", I go to sessions and no sessions are avaliable...
Is that a bug or my fault?

**Comment by Tajnymag** [comment]
The message "Job started" doesn't necesserilly mean, that the launched exploit was successful. It only means, that cSploit was able to run it and successfully ran it :)

**Comment by PTZema** [comment]
I think that was successful :/ I'm trying so hard hack my pc but the only exploit that says job started don't open the session... I think that is a bug or something
Thanks :)

**Comment by sorano** [comment]
Like Tajnymag said: "The message "Job started" doesn't necesserilly mean, that the launched exploit was successful. It only means, that cSploit was able to run it and successfully ran it".

So, most likely your computer was patched against the launched exploit and you did not get a session.

I would suggest testing against something like Metasploitable instead of your PC.
https://github.com/cSploit/android/wiki/%5BTutorial%5D-Use-cSploit-to-get-root-shell-on-Metasploitable2
