### ISSUE TITLE
Cannot start process

### ISSUE THREAD

**Issue by sythe179** [cSploit/android#367]
Htc m9 doesn't start the metasploit RPCD

**Comment by sythe179** [comment]
Latest version of csploit 
Htc m9, default rom.

All packages download and install, but fails to start the RPCD. I'll add a logcat when I am able to.

**Comment by newbie442** [comment]
Hey sythe179,

FWICT cSploit does a *lot* of updating/validating/installation of various files - it can take over 10 minutes on my pretty-fast connection (just took 12 minutes for tonights update of msf/gems #108). And that's when there is no interruption due to line condition, other apps grabbing resources, etc. Also, interrupts can occur which borks the whole operation.

Suggest you completely kill cSploit (reboot or do a memory purge) and restart. It'll ask if you want to update - at that point say yes and drag down the notification drawer and you'll see the action up there. You may have to do this two or three times - but it works for me!

HTH

**Comment by tux-mind** [comment]
Hi @newbie442 thanks for the tip, but that's not the way to solve bugs.
that's the way a windows PC works :laughing: 

@sythe179 provide a logcat and I'll work on it :wink: 

anyway we just released a stable version: [1.6.0](https://github.com/cSploit/android/releases/tag/v1.6.0)

give it a try :wink:
