### ISSUE TITLE
Question about password sniffer.

### ISSUE THREAD

**Issue by evertking** [cSploit/android#415]
Don't really know where to post questions on usage.. But how should you use the password sniffer? And does it work on android phones as the target? Does it check for stored passwords? 
Also, where can I fi d the irc chatroom as I guess that is the place to find answers to questions llike these?

**Comment by Tajnymag** [comment]
Password sniffer doesn't check for stored passwords. It checks for any non-encrypted login submition while you're capturing the network traffic.

**Comment by fat-tire** [comment]
@evertking basically it "listens" on the network for passwords being sent "in the clear" (not encrypted) and collects them.  [this article](http://www.wallofsheep.com/pages/wall-of-sheep) might give you some background on what it's doing...   it is a real reminder that you should use https rather than http (+ SSL/TLS for non web-traffic) whenever possible because otherwise your traffic is vulnerable to being intercepted in transit.

Take a look at the links at the bottom of [this tutorial](https://github.com/cSploit/android/wiki/%5BTutorial%5D-Use-cSploit-for-simple-Man-In-The-Middle-(MITM)-security-demos) for more info on why encryption is an absolute necessity for any type of transmission where you have some desire for privacy/security.

**Comment by gainan** [comment]
@evertking , if you still have questions on this matter, feel free to open the issue again. The irc chatroom is this: https://webchat.freenode.net/?channels=csploit
