### ISSUE TITLE
Cannot start commands

### ISSUE THREAD

**Issue by joehowlin** [cSploit/android#429]
Device: Moto G 2014 
Android 4.4.4
cSploit version: 1.6.2
When I open the app and connected to WiFi the below is added to the debug.log file.
Debug log:
>org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
>at org.csploit.android.tools.Tool.async(Tool.java:48)
>at org.csploit.android.tools.NMap.synScan(NMap.java:142)
>at org.csploit.android.tools.NMap.synScan(NMap.java:146)
>at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
>at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>at java.lang.Thread.run(Thread.java:841)

**Comment by tux-mind** [comment]
Hi @joehowlin thanks for the report, can you share the whole logcat of the core installation process ?

thank you in advance.

**Comment by joehowlin** [comment]
Here is the logcat http://pastebin.com/Ug8GF20V
I got the same error when I opened it on my tablet as well (Nvidia Shield running Android 5.1.1)

**Comment by gainan** [comment]
The problem is this:
> /data/data/org.csploit.android/files/tools/nmap/nmap-services: open failed: ENOENT (No such file or directory)
10-14 13:14:47.283 E/CSPLOIT[core.System.errorLogging](21442): java.io.FileNotFoundException: /data/data/org.csploit.android/files/tools/nmap/nmap-services: open failed: ENOENT (No such file or directory)
10-14 13:14:47.283 E/CSPLOIT[core.System.errorLogging](21442):  at libcore.io.IoBridge.open(IoBridge.java:456)
10-14 13:14:47.283 E/CSPLOIT[core.System.errorLogging](21442):  at java.io.FileInputStream.<init>(FileInputStream.java:76)
10-14 13:14:47.283 E/CSPLOIT[core.System.errorLogging](21442):  at java.io.FileInputStream.<init>(FileInputStream.java:103)
10-14 13:14:47.283 E/CSPLOIT[core.System.errorLogging](21442):  at java.io.FileReader.<init>(FileReader.java:66)
10-14 13:14:47.283 E/CSPLOIT[core.System.errorLogging](21442):  at org.csploit.android.core.System.preloadServices(System.java:552)

We load the vendors and macs even if the core tools are not installed.

**Comment by joehowlin** [comment]
I do have the core tools installed though.

**Comment by joehowlin** [comment]
I have just checked the nightly version and the error is still there.
Here is logcat http://pastebin.com/rJmCLPxx

**Comment by Silur** [comment]
same here
