### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by MusicaFM** [cSploit/android#473]
Not compatible with Hisense u961, please solution already, please, Thank you, If you can answer me in Spanish

**Comment by xaitax** [comment]
https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by gainan** [comment]
@MusicaFM , please, tell us which version are you using and what is not working for you, otherwise we're unable to help you. Read the link @xaitax has posted, and follow the steps to report bugs properly please.

Dinos por favor qué versión estás usando y qué es lo que no te funciona, porque si no no vamos a poder ayudarte... lee el enlace de xaitax y sigue los pasos que pone ahí para reportar bugs :)

**Comment by gainan** [comment]
reopened on #477
