### ISSUE TITLE
Suggestion: UsbCleaver/Rubberducky integration

### ISSUE THREAD

**Issue by uranium-waffles** [cSploit/android#496]
I was thinking maybe we could add something that would allow command execution different payloads that. Dump System Information Dump IE Passwords Dump Chrome Passwords Dump Firefox Passwords Dump Wifi Passwords and dumb basically any passwords found and run scripts which go back towards the concept of csploit. The script below enters the command shell as administrator, disable the firewall and exports the wifi settings then send to an ftp server of your choice. After sending the file it will delete the exports from the sending directory and restore the firewall. https://github.com/hak5darren/USB-Rubber-Ducky/wiki/Payload---WiFun-v1.1 this would be good for csploit and I can't do this myself at least not yet because I am just now getting used to android studio.

**Comment by uranium-waffles** [comment]
Sorry for the spelling error at the top

**Comment by fat-tire** [comment]
If I'm not mistaken, Rubber ducky requires modifications to the kernel.  If you're interested in doing this however, you should check out [Nethunter](https://www.kali.org/kali-linux-nethunter/) which provides the needed kernel for many devices.  I know more are on the way because I've been contributing a bit to that project as well-- the [new 2.1 app](https://github.com/offensive-security/nethunter-app/tree/master-2.1) will only require an app + optionally a modified client, so it will be easier to port to new devices.  The current 2.0 version must be distributed as part of a full Android ROM, which makes it a big harder to port and maintain and significantly bigger to download.

Anyway, yeah-- this is a very very old screenshot, but as you can see Rubberducky is in and working.

<img src="https://www.offensive-security.com/wp-content/uploads/2015/05/hid-ducky-script-convert-1024x576.png" width="400px"/>

**Comment by uranium-waffles** [comment]
@fat-tire Alright, thank you for the info, I'll definitely look at that.
