### ISSUE TITLE
Problem with cyrillic encoding

### ISSUE THREAD

**Issue by ddych** [cSploit/android#50]
When using MITM, there is a problem with encoding on target device. Not at all sites. I think it because some sites use windows-1251. I test it in images replacing and video replacing modes. For example:
![screenshot_2015-01-28-00-58-23](https://cloud.githubusercontent.com/assets/10694999/5937517/c60e2324-a733-11e4-87e6-60426663abc3.png)
![screenshot_2015-01-28-00-58-02](https://cloud.githubusercontent.com/assets/10694999/5937534/0a4e8060-a734-11e4-86ec-dd86838882b4.png)
Other browser:
![screenshot_2015-01-28-00-53-45](https://cloud.githubusercontent.com/assets/10694999/5937564/494cefe0-a734-11e4-8e0b-86dc57b7c5de.png)

I haven't tested all modes. Can you fix it please?
Thanks.

**Comment by tux-mind** [comment]
Hi @ddych this bug will be fixed when the `evilproxy` program sobstitute the current Java proxy.

will close this when we made it.
probably will require some months because the list of bugs is quite long as now and writing a proxy in C is a very time consuming task.

BTW I will certainly do this. is the main reason why we build the new core.

it will be of great help if someone else can help me on this project, I cannot spend all my time on cSploit, i have to study and work for pay the college bill.

thanks anyway for the report :blush:

**Comment by ddych** [comment]
Thank you for response,
I assumed that you know about this issue. Unfortunately, I'm not good at programming, and can not offer help (

**Comment by gainan** [comment]
fixed on #479.
