### ISSUE TITLE
Not trusted connection on sniffered machine

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#501]
Hi! Find new problem. Have a pc with latest firefox or chrome. While i sniff session with ssl strip func on and try to go to https have message on pc that connection with certificate csploit.org isn't trusted and i can't go to the site. if u don't understand me sniff session on your pc and try to go to https://voipnum.com/

**Comment by gainan** [comment]
you are right @0MazaHacka0 , that's the expected behaviour. We use a ssl self signed certificate, so it's normal that you see that warning, because your browser not only realizes that the CommonName of the certificate doesn't match the domain you are connecting to, but also because it realizes that it's a self signed certificate. As it doesn't have the CA certificate on its internal db of trusted certificates, it displays the user a warning.

We don't generate ssl certificates on the flight either for the domain the user is connecting to, so for now, if you enable sslstripping on cSploit, the victim will see a warning whenever it tries to connect to a HTTPS site.

On the other hand, when the sslstrip option is enabled, whenever we see a https:// URL on a website or on the client's request, we rewrite it to http://. I would separate this feature from intercepting HTTPS connections, adding a new option to the settings.

**Comment by 0MazaHacka0** [comment]
OK, thanks

**Comment by fat-tire** [comment]
In other words-- the warning from your browser is a *good* thing as it means that the browser has detected that https has likely been MITM'd and therefore the browser is warning you.  This is what you want to happen when the replaced and the browser is warning you appropriately.  Gainan mentioned that an alternate type of attack might be to downgrade https:// to http://,but in this situation the "target" would hopefully notice the lack of a "lock" icon in their browser.

**Comment by gainan** [comment]
funny you mentioned the lack of lock icon. We could replace the favicon of a web site with a lock icon, like sslstrip does. This trick doesn't work on "modern" browsers (firefox, chrome..), but maybe it will on others. http://www.slideshare.net/SecurityTube.Net/black-hat-dc-09-marlinspike-defeating-ssl

by the way, we could add more mime types to filter, like xml, json and rss (and derivatives). It's usual to see https links on these files, and they are sent through the port 80/443. Many websites perform ajax requests on background for download content from (rest) webservices, which as far as I've seen is usual to be in json format.
