### ISSUE TITLE
android>csploit>rudy

### ISSUE THREAD

**Issue by 28616847** [cSploit/android#516]
ruby.tar.xz          can't install

**Comment by maddog9696** [comment]
As smart as some of these devs are, you don't really think they can help you solve your issue with the info you provided, do you!? Come on! Lol  
I suggest you read this page carefully: https://github.com/cSploit/android/wiki/How-to-open-an-issue
Please include logs and device specifics when filing a bug!
Thanks

**Comment by fat-tire** [comment]
Since no logs were provided by random number guy, I decided to look at these logs to see if I could get to the root of the problem. 

<img src="http://previews.123rf.com/images/koya79/koya791211/koya79121100175/16598330-stack-of-firewood-logs-on-white-background-Stock-Photo-wood.jpg" width="200px"/>

If I'm interpreting them correctly, it seems you have tried to install ruby.tar.xz to an egg salad sandwich. Try using an Android phone.  cSploit is not meant to be run on food.

**Comment by fat-tire** [comment]
No further comment?  I'm closing this.  Please re-open if the issue exists on a recent build.

**Comment by tux-mind** [comment]
@fat-tire you make me smile a lot :joy: :joy: :joy: :joy:
