### ISSUE TITLE
Add an options to change the MSF and Ruby location to the external SD Card

### ISSUE THREAD

**Issue by sourc7** [cSploit/android#519]
At default, cSploit download and install the MSF and Ruby to the phone internal location (/data/data/*).

cSploit have an options to change the location path, but I can't change the location except change the path to /storage/emulated/0/* (choose 0).

**Comment by fat-tire** [comment]
I think the files you want to change are [here](https://github.com/cSploit/android/blob/d93d6c50cfd31eb5bb51c6c22c107ac9a8effbef/cSploit/src/main/java/org/csploit/android/core/System.java#L519-L537).  There are some caveats with using external storage tho--

1.  It requires a permission if you want to write to a public (non-app specific) area of external storage via getExternalStoragePublicDirectory. cSploit kinda needs root so this isn't a big deal...

2.  More responsible would be to use Context.getExternalFilesDir() which doesn't need a permission... but...

3.  Starting in MM, there is a possibility that the external storage can be "adopted" by the user-- which could cause some complications here if they do that without realizing the consequences, which I think would involve losing the installed files... (I haven't tried adopting external storage so i don't know how this works yet).  I also believe this breaks paths (Google makes a big point about not using paths but instead URIs...) and now you're using ext4 rather than whatever (FAT32?) you were using before...

4.  In fact, would msf/ruby need permissions, file user/groups, or other features that may not exist in the typical external storage filesystem?  if so, that may be an issue.

5.  Finally, SDCards can be removed, which could also cause problems.  [getExternalStorageState()](http://developer.android.com/reference/android/os/Environment.html#getExternalStorageState()) would probably need to be called every time just to make sure it hasn't been (re)moved.

Just out of curiosity, what's your reason for wanting to put this in external storage?  Would you be okay with it being in the designated app sandbox there?

**Comment by tux-mind** [comment]
thank you for the very detailed explanation @fat-tire ! :blush: 

I just read about adoptable storage, it should not affect cSploit, except for migrating from path to URIs.

about FAT32, cSploit will check for the required permission capability of the destination FS and deny to change the path if those requirements are not satisfied.
