### ISSUE TITLE
Ideas.

### ISSUE THREAD

**Issue by pahapoika** [cSploit/android#526]
1 Android Vulnerability finder module.
Would access you to scan if your android phone is exploitable for stagefright etc. Would include exploits too.

2.Upgrade Vulnerability finder to hack VNC connections

3.Bluethooth hack.
Add module like https://play.google.com/store/apps/details?id=it.medieval.blueftp&hl=fi&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dbt+file+transfer&pcampaignid=APPU_1_J2FkVr_mDub7ygPLirTgDg but little bit upgraded.

4.vulnerability finder could be more effective.

**Comment by pahapoika** [comment]
5.Armitage module.
Could add module like armitage.

**Comment by fat-tire** [comment]
1.  Why not just use [this](https://play.google.com/store/apps/details?id=com.zimperium.stagefrightdetector)?  The purpose of cSploit isn't to find vulnerabilities on the device you are currently running (cSploit requires root privilages, after all)

2. By what method?

3.  Huh?

4.  Please be more specific.

5.  [Armitage](https://github.com/ccdc/armitage) uses [swing](https://en.wikipedia.org/wiki/Swing_(Java)) extensively, but please feel free to port it if you think that armitage's UI would port over nicely to Android's touch interface.  That said, there is already some limited Metasploit Android-style UI, with more in the works.

**Comment by pahapoika** [comment]
1 or that would be android exploit finder. First it would scan for vulnerabilites like stagefright and then it would show you exploit for that vulnerability. 

2. Open VNC connections.

4.could include more MSF Features and could include exe that opens backdoor. exe would be named as internet explorer or something. Could include payload too.

**Comment by pahapoika** [comment]
1. Would be for other android devices in your wifi

**Comment by tux-mind** [comment]
thank you for sharing your ideas with us @pahapoika , I think that @fat-tire already answered you.

Once a time there was a vulnerability finder, but it has been removed because it give a lot of false positive matches and many of them was not useful.
Just think about your vulnerability finder for the stagefright, it should take into account only android phones, but you have no way to understand if a device it's an android phone or a server ( nmap can **guess** it, but you are not sure ), so you have to run the test against all found devices in the network.

As now cSploit will search directly for compatible exploits using OSVDB and CVE.
Now you have only the compatible exploits with the vulnerability as a detail ( as MSF does ).

VNC, backdoor and other stuff will come in with the new MSF implementation in cSploit 2.

I think that cSploit 2 it's something like armitage for android, it will give you a simple interface to the MSF.

**Comment by tux-mind** [comment]
Bluetooth was proposed, but we noticed that there are already other app that does the trick very well, so we avoid to reinvent the wheel and let you use those apps :stuck_out_tongue_closed_eyes:
