### ISSUE TITLE
copyleft & bettercap integration

### ISSUE THREAD

**Issue by pahapoika** [cSploit/android#551]
As title says this is not issue just question. But does evilsocket still have the copylefts. As csploit_copyleft says? And @tux-mind maybe you can use evilsockets new MiTM project (bettercap)in cSploitt new MiTM ?

**Comment by tux-mind** [comment]
when I asked about what is the copyleft the answer was: nothing.
copyleft it's just a joke about the copyright word and does not imply any intellectual property.
on the other hand the GPL it's clear, we must cite the previous owner of the code.
but I have to say that major part of the sources has been rewritten entirely... by me.

when I gave a look to the bettercap project I saw that it does not have an API, it just print on the screen what it find. also there is not only one printing routine, every dissector has it's own way to print the results ( or info ).
this make it very difficult to interact with such program.

also it require ruby with some gem to be cross-compiled... isn't a trivial task...

my suggestion was to start a new project named evilproxy ( in honor to evilsocket ), which will have all the current MitM features plus some new cool stuff like SSL split and so on.

The problem is that I have no time to develop such program, not now.
I gave this hard task to a collaborator ( @n3vermind ), which started working on the [evilproxy](https://github.com/cSploit/evilproxy) project.
I hope to resume working on this project soon, but I have many other things to manage: the [new build system](https://github.com/cSploit/botbrew), a new [msf interaction](https://github.com/cSploit/android/tree/msf_restyling), a new [UI](https://github.com/cSploit/android/pull/492) ...

**Comment by pahapoika** [comment]
Oh okey. I just thing that maybe evilsocket would like to  make the MiTM module to cSploit but evilproxy sounds intresting too.

**Comment by Cursewords** [comment]
Don't overload yourself too much my friend. I sent a small donation for work done thus far. Better that updates are slow and steady than development just burning out. 

I'll consider subscribing donations so something can be sent per month. I'm just currently unaware about specifics of the project. eg. how many people are working on it.

**Comment by pahapoika** [comment]
@Cursewood Suomi perkele! :)

**Comment by pahapoika** [comment]
@Cursewoods

**Comment by pahapoika** [comment]
Woow im writing this with phone and the auto correction freaks me out. 👽 So one last time @Cursewords
