### ISSUE TITLE
double confirm to exit

### ISSUE THREAD

**Issue by rigid** [cSploit/android#63]
Not an important issue, but could annoy users. Imo either double-back (press back again to exit) or the confirmation requester (really exit? yes/no) would be enough. are both really needed?

**Comment by fabinhojcr** [comment]
In my opinion I think it is necessary but it avoids closing the application inadvertently.

**Comment by rigid** [comment]
At the moment, for me, it'd be more useful if it would be less annoying to quickly restart csploit.
But since this seems to be a matter of taste, i think it's better to leave the decision to the maintainer(s). :)

**Comment by tux-mind** [comment]
I think you're right @rigid .

I think that the `cSploitd` and `msfrpcd` will not impact the battery life if still running.
they just keep a socket opened on your localhost ( a UNIX and a TCP one ).

the problem is `network-radar`, it can kill your battery quickly.
IMHO, the best solution is to stop the radar when cSploit is not a foreground activity.

so the application will never "exit". it just close the UI, but the found targets, ports and exploits still there.

obviously this means a little more work on the programming side, we have to manage strange states, like having targets but the wifi went down.

as I said time ago ( when the project name was dSploit ) the following scanario it's a cool feature:

  - on break you start cSploit to scan the network and find Exploits.
  - you find some open ports on some hosts, but your break is over.
  - come back to your classroom and notice that the wifi signal is lost.
  - start searching for exploits using your 3G connection.
  - come back to the relax area and connect to the AP.
  - launch found exploits.
  - take a coffe :coffee: 

but I really need more programmers, I have to focus on the core to add missing features like MITM, using WiFi USB dongles and more ...

**Comment by sorano** [comment]
This has been commited already.
Nowadays you get "Press back again to close" then a prompt "This will close cSploit, are you sure?"
Im closing this.
