### ISSUE TITLE
csploitd.log (and logcat) auto-paste issue reporting

### ISSUE THREAD

**Issue by rigid** [cSploit/android#64]
It would rock if the in-app "submit issue" mechanism could automatically add the current csploitd.log and a logcat to an issue (maybe optionally, with a checkbox).

**Comment by tux-mind** [comment]
cool feature, any suggestion of where to put the logcat and the core log ?

pastebin require an API key
github gist require a github account

any other suggestion ?

putting the log into the issue body is unacceptable...

**Comment by rigid** [comment]
doesn't gist support anonymous pastes?
Would creating some dummy github account be an option maybe?

**Comment by fat-tire** [comment]
FWIW there is http://www.acra.ch/ (I haven't used it) see also https://github.com/ACRA/acra

**Comment by tux-mind** [comment]
thanks for the suggestion @fat-tire .

working on this.
I need the full logcat for debug native component crashes.

**Comment by sorano** [comment]
@tux-mind this issue has been solved right?
There is crash report in the app, and I've seen you talk about acra reports.

**Comment by tux-mind** [comment]
yeah it works great for Java errors, and it report the entire logcat ( containing native stuff ) in case of a native crash.

the missing thing is how to connect it to github.
after a report there is no way to get back it's ID from ACRA, so we cannot open an issue on github linking the report ID.

will also fix #365 , because no user action is required.
