### ISSUE TITLE
MITM session hijacker https redirecting problem

### ISSUE THREAD

**Issue by zi-nou** [cSploit/android#693]
hi hwo could help me i can't redirect the facebook page from https to http

**Comment by IwraStudios** [comment]
See https://github.com/cSploit/android/issues/689 
it's because the current sslstrip can only redirect if it's coming from an unsecure website say:
random http website --> google(https)
that would result in google being http 
but say:
google --> google
or
nothing -->google
would still result in https

**Comment by IwraStudios** [comment]
we could fix this in the future (https://github.com/cSploit/android/issues/680) but there are some compatability problem

**Comment by zi-nou** [comment]
i was able to redirect the fb page from https to http ..i've entered my e-mail and password in my pc and i hacked it with csploit but after that when i want to redirect the fb page from https to http 
Thanks for ur help and sorry for my english am from algeria so i don't speek it fluently :) ^^
