### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BearChavez** [cSploit/android#894]
DEVICE: iPhone

OS version: Any

**cSploit version:**

**busybox** *(installed or not):*

**Rooted with supersu?**

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

I would be happy to test out iOS builds and potentially help develop them, but I would need training for the development

**Comment by tux-mind** [comment]
Hi @BearChavez , thank you for you willing to help us.

Yes, iOS is on the road map but the current main target is Android.
To make cSploit working on iOS you should build the daemon for the iOS platforms ( arm64 and others, depending on the device AFAIK ).
Then a simple http server that serve the client will do the rest :blush: 
Some features will not be enabled on the iOS platform due to the ( as now ) missing tools.


Please join us on [slack](https://csploit.slack.com) :)

**Comment by fabinhojcr** [comment]
@tux-mind Send me an invitation to join slack

**Comment by BearChavez** [comment]
@tux-mind I need an invitation to join. My email is _secret_

**Comment by tux-mind** [comment]
Done for both :blush: 

@fabinhojcr I took your email from an old commit from you :wink:

**Comment by fabinhojcr** [comment]
Thanks @tux-mind

**Comment by BearChavez** [comment]
@tux-mind Apple devices don't use ARM processors, I don't know if that changes how it's built, but they are very different from each other

**Comment by tux-mind** [comment]
I'm pretty sure that iPhone devices are ARM based, please check and let me
know :)

AFAIK if the target platform is supported by the Go compiler we're ready to
proceed. But I didn't check it yet.

Best regards, tux_mind :)

Il 22 ago 2017 12:34 AM, "BearChavez" <notifications@github.com> ha scritto:

**Comment by BearChavez** [comment]
@tux-mind I was wrong, they are ARM based, sorry about that
