### ISSUE TITLE
MSF RPC not connected

### ISSUE THREAD

**Issue by Msrpc** [cSploit/android#98]
Selected target > Sessions 

Gives error: MSF RPC not connected

Even though it says MetasploitRPCD and Network monitor are running 

Even after running port scanner, Inspector, Vulnerability finder, Exploit finder.

**Comment by greensmith** [comment]
What port does your MSFRPCD run under (default is 55553)?
I have noticed problems with this setting and sometime there are issues changing it.

What does a terminal reply with when you run these commands?

ps aux | grep 'msf'
this should show the cmd used to run the daemon (something like ruby /data/msfrpcd......)

netstat -a
this should show with the daemon (or anything) is listening and what what

**Comment by greensmith** [comment]
I have noticed that on a fresh installation
this is being run

*ruby /data/data/org.csploit.android/files/msf/msfrpcd -P msf -U msf -p* ***5553*** *-a 127.0.0.1 -n -S -t Msg -f*

notice the port.
Seems this commit missed a 5 from MSF_RPC_PORT?
https://github.com/cSploit/android/commit/2f223ab787c5a9690c4250e35c420267a611f48f


Also, the daemon is listening on 127.0.0.1 rather than 0.0.0.0 so only local connection are allowed. May I suggest altering this to allow other devices to connect to the daemon?

**Comment by Msrpc** [comment]
@greensmith is there a manual fix for this? 

ps aux | grep 'msf' didn't show anything for me 

netstat -a showed 

                local address.           foreign address
tcp        127.0.0.1:55553              0.0.0.0:*

udp.        0.0.0.0:48061                 0.0.0.0:*


Kinda confused what is the 0.0.0.0:4861 is it just looking at the wrong port 55553?

**Comment by MatthewHKnight** [comment]
I'm getting an error trying to start Metasploit RPCD says, cannot start progress.
Not sure if its an issue because i have nethunter installed having this issue on a Nexus 7 2013 WiFi Tablet.

**Comment by sorano** [comment]
Duplicate of #205
Try the latest version.
